import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
  en: {
    home: 'Home',
    favorites: 'Favorites',
    signIn: 'Sign In',
    getStarted: 'Get Started',
    signOut: 'Sign Out',
    dashboard: 'Dashboard',
    addProperty: 'Add Property',
    adminPanel: 'Admin Panel',
    activeListings: 'active listings nationwide',
    heroTitle: 'Find Your Perfect Home, Smarter.',
    heroSubtitle: 'Search millions of listings with intelligent filters, instant alerts, and verified agents — all in one place.',
    buy: 'Buy',
    rent: 'Rent',
    searchLocation: 'City, neighborhood, or ZIP code',
    searchHomes: 'Search Homes',
    activeListingsCount: 'Active Listings',
    citiesCovered: 'Cities Covered',
    happyBuyers: 'Happy Buyers',
    agentPartners: 'Agent Partners',
    handPicked: 'Hand-Picked',
    featuredProperties: 'Featured Properties',
    viewAllListings: 'View all listings',
    beds: 'beds',
    baths: 'baths',
    sqft: 'sqft',
    viewDetails: 'View Details',
    whyChooseUs: 'Why UrbanNest',
    featuresTitle: 'Everything you need to find home',
    signInTo: 'Sign in to UrbanNest',
    dontHaveAccount: "Don't have an account?",
    createOneFree: 'Create one free',
    orContinueWith: 'or continue with email',
    emailAddress: 'Email address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    rememberMe: 'Remember me for 30 days',
    termsAndPrivacy: 'By signing in, you agree to our',
    terms: 'Terms',
    and: 'and',
    privacyPolicy: 'Privacy Policy.',
    quickDemoLogin: 'Quick demo login',
    createYourAccount: 'Create your account',
    alreadyHaveOne: 'Already have one?',
    iWantToBuyRent: 'I Want To Buy/Rent',
    iWantToSellList: 'I Want To Sell/List',
    firstName: 'First name',
    lastName: 'Last name',
    confirmPassword: 'Confirm password',
    minChars: 'Min. 8 characters',
    repeatPassword: 'Repeat password',
    agreeTo: "I agree to UrbanNest's",
    termsOfService: 'Terms of Service',
    privacyPolicyLink: 'Privacy Policy.',
    createAccount: 'Create Account',
    totalPosted: 'Total Posted',
    activeListingsTab: 'Active Listings',
    pending: 'Pending',
    rejected: 'Rejected',
    myProperties: 'My Properties',
    savedFavorites: 'Saved Favorites',
    noProperties: 'No properties yet',
    addFirstProperty: 'Add Your First Property',
    noFavorites: 'No saved favorites yet',
    browseProperties: 'Browse Properties',
    listedBy: 'Listed by',
    verifiedAgent: 'Verified Agent',
    scheduleViewing: 'Schedule a Viewing',
    mortgageEstimate: 'Mortgage Estimate',
    mortgageSubtitle: '30-yr fixed at 6.8% APR, 20% down',
    perMonth: '/month',
    estimateDisclaimer: '* Estimate only. Contact a lender for exact terms.',
    shareThisProperty: 'Share this property',
    copyLink: 'Copy link',
    email: 'Email',
    save: 'Save',
    aboutThisProperty: 'About this property',
    similarProperties: 'Similar Properties',
    overview: 'Overview',
    features: 'Features',
    contact: 'Contact',
    built: 'Built',
    area: 'Area',
    parking: 'Parking',
    cars: 'cars',
    contactOwner: 'Contact Owner',
    callOwner: 'Call Owner',
    chatOnViber: 'Chat on Viber',
    signInToContact: 'Sign in to contact the owner',
    addNewProperty: 'Add New Property',
    editProperty: 'Edit Property',
    fillDetails: 'Fill in the details to list your property',
    propertyInfo: 'Property Info',
    basicDetails: 'Basic property details',
    specifications: 'Specifications',
    sizeAndLayout: 'Size and layout',
    description: 'Description',
    tellUsMore: 'Tell us more',
    media: 'Media',
    uploadPhotos: 'Upload photos',
    propertyTitle: 'Property Title',
    listingType: 'Listing Type',
    forSale: 'For Sale',
    forRent: 'For Rent',
    price: 'Price (MMK)',
    township: 'Township',
    selectLocation: 'Select location',
    sqftLabel: 'Sq Ft',
    address: 'Address',
    fullAddress: 'Full property address',
    descriptionLabel: 'Description',
    descPlaceholder: 'Describe your property in detail...',
    featuresLabel: 'Features & Amenities',
    dragDrop: 'Drag and drop your photos here',
    orClickToBrowse: 'or click to browse',
    chooseFiles: 'Choose Files',
    uploadAtLeast: 'Upload at least 1 photo. Recommended size: 1200x800px',
    previous: 'Previous',
    next: 'Next',
    submitForApproval: 'Submit for Approval',
    propertySubmitted: 'Property Submitted!',
    submittedDesc: 'Your property has been submitted for approval.',
    redirecting: 'Redirecting to dashboard...',
    adminDashboard: 'Admin Dashboard',
    totalUsers: 'Total Users',
    totalProperties: 'Total Properties',
    pendingApprovals: 'Pending Approvals',
    manageData: 'Manage Data',
    approve: 'Approve',
    reject: 'Reject',
    featuresAmenities: 'Features & Amenities',
    navHowItWorks: 'How It Works',
    navKnowledge: 'Knowledge',
    navLoanCalc: 'Loan Calculator',
    howKicker: 'How It Works',
    howTitle: 'How UrbanNest Works',
    howSub: 'A simple, transparent process connecting property seekers with their perfect spaces.',
    aboutBuyerJourney: 'Buyer Journey',
    aboutSellerJourney: 'Seller Journey',
    aboutStepSearch: 'Search Properties',
    aboutStepSearchDesc: 'Browse listings by location, price, type, and more.',
    aboutStepDetails: 'View Details',
    aboutStepDetailsDesc: 'See photos, descriptions, and property specifications.',
    aboutStepFavorites: 'Save Favorites',
    aboutStepFavoritesDesc: 'Heart any listing to save it for later.',
    aboutStepContact: 'Contact Owner',
    aboutStepContactDesc: 'Call or message the property owner directly.',
    aboutStepCreate: 'Create Listing',
    aboutStepCreateDesc: 'Fill in property details and upload photos.',
    aboutStepSubmit: 'Submit for Review',
    aboutStepSubmitDesc: 'Your listing goes to admin for approval.',
    aboutStepApproval: 'Admin Approval',
    aboutStepApprovalDesc: 'Admin reviews and approves your listing.',
    aboutStepLive: 'Listing Goes Live',
    aboutStepLiveDesc: 'Your property appears on UrbanNest.',
    faqTitle: 'Frequently Asked Questions',
    faqSub: 'Find quick answers to the most common questions about UrbanNest.',
    faqCatAll: 'All',
    faqCatGeneral: 'General',
    faqCatListing: 'Property Listing',
    faqCatBuying: 'Buying',
    faqCatSelling: 'Selling',
    faqCatAccount: 'Account',
    faqCatTechnical: 'Technical',
    faqCtaTitle: 'Still have questions?',
    faqCtaSub: "Can't find what you're looking for? Our support team is ready to help.",
    faqCtaBtn: 'Contact Support',
    faq1Q: 'How do I list a property?',
    faq1A: 'Sign in, open Add Property, complete the 4-step form and submit. Your listing starts as Pending and appears in your dashboard.',
    faq2Q: 'Why is my property listing pending?',
    faq2A: 'Every new or edited listing must be reviewed by an admin before it is shown publicly. Check the status in your dashboard.',
    faq3Q: 'How do I contact a property owner?',
    faq3A: 'Open the property details page and use the Call Owner button or the owner phone shown. Sign in to see owner contact information.',
    faq4Q: 'How do I save a property to favorites?',
    faq4A: 'Tap the heart icon on any listing. Saved items appear in Dashboard → Saved Favorites.',
    faq5Q: 'How can I edit or delete my property listing?',
    faq5A: 'Go to Dashboard → My Properties, then use the Edit or Delete actions next to the listing.',
    faq6Q: 'How do I report a listing?',
    faq6A: 'Use the contact form and choose Report a Listing, or email contact@urbannest.com with the property details.',
    faq7Q: 'What is UrbanNest?',
    faq7A: 'UrbanNest is a modern real estate platform that helps you discover, list, and manage properties in Myanmar. It is a university graduation project.',
    faq8Q: 'Is UrbanNest free to use?',
    faq8A: 'Yes. Browsing, searching, saving favorites, and listing properties are all completely free.',
    faq9Q: 'What photos do I need for my listing?',
    faq9A: 'Upload clear photos of the property exterior, interior rooms, kitchen, bathroom, and any special features. High-quality photos help attract more buyers.',
    faq10Q: 'How do I search for properties?',
    faq10A: 'Use the search bar on the Home page. You can filter by location, property type, price range, and keyword to find what you need.',
    faq11Q: 'How do I create an account?',
    faq11A: 'Click Get Started or Sign In, then switch to the Register tab. Fill in your username, email, and password to create your account.',
    faq12Q: 'How do I reset my password?',
    faq12A: 'On the login page, click Forgot Password and follow the instructions sent to your email address.',
    faq13Q: 'How do I update my profile information?',
    faq13A: 'Go to Dashboard and click on your profile section. From there you can update your username, email, and avatar.',
    faq14Q: 'How do I delete my account?',
    faq14A: 'Contact our support team through the Contact page and request account deletion. We will process your request within 48 hours.',
    loanCalcTitle: 'Home Loan Calculator',
    loanCalcSub: 'Estimate your monthly mortgage payments. This is a free estimation tool — UrbanNest does not provide or process loans.',
    loanCalcAmount: 'Loan Amount',
    loanCalcRate: 'Interest Rate (%)',
    loanCalcTerm: 'Loan Term (Years)',
    loanCalcBtn: 'Calculate',
    loanCalcMonthly: 'Monthly Payment',
    loanCalcPrincipal: 'Principal',
    loanCalcInterest: 'Interest',
    loanCalcSummary: 'Loan Summary',
    loanCalcSchedule: 'Repayment Schedule',
    loanCalcDisclaimer: 'This calculator provides estimates only. Actual rates and terms may vary. UrbanNest is not a lender and does not process loan applications.',
    loanCalcYear: 'Year',
  },
  my: {
    home: 'အိမ်',
    favorites: 'ကြိုက်နှစ်သက်',
    signIn: 'ဝင်ရောက်',
    getStarted: 'စတင်',
    signOut: 'ထွက်',
    dashboard: 'ဒက်ရှ်ဘုတ်',
    addProperty: 'အိမ်ထည့်',
    adminPanel: 'Admin Panel',
    activeListings: 'တိုင်းဒေသကြီးတစ်ဝိုက် အိမ်ခြံမြေ စာရင်းများ',
    heroTitle: 'သင့်အိမ်အကောင်းဆုံးကို ပိုမိုလွယ်ကူစွာ ရှာဖွေပါ။',
    heroSubtitle: 'ဉာဏ်ရည်တု စစ်ထုတ်မှုများ၊ ချက်ချင်း သတိပေးချက်များနှင့် အတည်ပြုထားသော အေဂျင့်များဖြင့် စာရင်းပေါင်းများစွာကို ရှာဖွေပါ။',
    buy: 'ဝယ်',
    rent: 'ငှား',
    searchLocation: 'မြို့နယ်၊ ရပ်ကွက် သို့မဟုတ် ZIP code',
    searchHomes: 'အိမ်များ ရှာဖွေပါ',
    activeListingsCount: 'လက်ရှိ စာရင်း',
    citiesCovered: 'မြို့ပေါင်း',
    happyBuyers: 'ပျော်ရွှင်သော ဝယ်ယူသူများ',
    agentPartners: 'Agent ပူးပေါင်းဆောင်ရွက်သူများ',
    handPicked: 'ရွေးချယ်ထားသည်',
    featuredProperties: 'အထူးချွတ် အိမ်ခြံမြေများ',
    viewAllListings: 'စာရင်းအားလုံးကြည့်ရန်',
    beds: 'အိပ်ခန်း',
    baths: 'ရေချိုခန်း',
    sqft: 'စတုရန်းပေ',
    viewDetails: 'အသေးစိတ်ကြည့်ရန်',
    whyChooseUs: 'ဘာကြောင့် UrbanNest ကို ရွေးချယ်သင့်သလဲ',
    featuresTitle: 'သင့်အိမ်အကောင်းဆုံးကို ရှာဖွေရန် လိုအပ်သမျှ',
    signInTo: 'UrbanNest သို့ ဝင်ရောက်ပါ',
    dontHaveAccount: 'အကောင့် မရှိသေးပါလား?',
    createOneFree: 'အခမဲ့ ဖန်တီးပါ',
    orContinueWith: 'သို့မဟုတ် email ဖြင့် ဆက်လက်ပါ',
    emailAddress: 'အီးမေးလ်',
    password: 'စကားဝှက်',
    forgotPassword: 'စကားဝှက် မေ့နေပါသလား?',
    rememberMe: 'ရက် ၃၀ အတွက် မှတ်ထားပါ',
    termsAndPrivacy: 'ဝင်ရောက်ခြင်းဖြင့် သင်သည်',
    terms: 'စည်းမျဉ်းများ',
    and: 'နှင့်',
    privacyPolicy: 'ကိုယ်ရေးမူဝါဒကို သဘောတူပါသည်။',
    quickDemoLogin: 'အမြန် demo ဝင်ရောက်မှု',
    createYourAccount: 'သင့်အကောင့်ကို ဖန်တီးပါ',
    alreadyHaveOne: 'ရှိပြီးသားလား?',
    iWantToBuyRent: 'ဝယ်/ငှား လိုပါသည်',
    iWantToSellList: 'ရောင်း/စာရင်းတင် လိုပါသည်',
    firstName: 'နာမည်',
    lastName: 'အမည်နောက်ဆက်တွဲ',
    confirmPassword: 'စကားဝှက် အတည်ပြုပါ',
    minChars: 'အနည်းဆုံး စာလုံး ၈ လုံး',
    repeatPassword: 'စကားဝှက် ထပ်ရေးပါ',
    agreeTo: 'UrbanNest ၏',
    termsOfService: 'ဝန်ဆောင်မှု စည်းမျဉ်းများ',
    privacyPolicyLink: 'ကိုယ်ရေးမူဝါဒကို သဘောတူပါသည်။',
    createAccount: 'အကောင့်ဖန်တီးပါ',
    totalPosted: 'စုစုပေါင်း တင်ထားသည်',
    activeListingsTab: 'လက်ရှိ စာရင်း',
    pending: 'စောင့်ဆိုင်းနေသည်',
    rejected: 'ငြင်းဆိုထားသည်',
    myProperties: 'ကျွန်ုပ်၏ အိမ်ခြံမြေများ',
    savedFavorites: 'သိမ်းဆည်းထားသည်',
    noProperties: 'အိမ်ခြံမြေ မရှိသေးပါ',
    addFirstProperty: 'သင့်ပထမဆုံး အိမ်ခြံမြေကို ထည့်ပါ',
    noFavorites: 'သိမ်းဆည်းထားခြင်း မရှိသေးပါ',
    browseProperties: 'အိမ်ခြံမြေများ ကြည့်ရန်',
    listedBy: 'စာရင်းတင်သူ',
    verifiedAgent: 'အတည်ပြုထားသည့် Agent',
    scheduleViewing: 'ကြည့်ရန် ချိတ်ဆက်ပါ',
    mortgageEstimate: 'အိမ်ခြံမြေ ချေးငွေ ခန့်မှန်းချက်',
    mortgageSubtitle: '၃၀-နှစ် ရည်မှန်းချက် ၆.၈% APR၊ ၂၀% ဖြည့်',
    perMonth: '/လ',
    estimateDisclaimer: '* ခန့်မှန်းချက်သာ။ တိကျသည့် စည်းကမ်းချက်များအတွက် ချေးငွေလက်ခံသူကို ဆက်သွယ်ပါ။',
    shareThisProperty: 'ဤအိမ်ခြံမြေကို မျှဝေပါ',
    copyLink: 'လင့်ခ် ကူးယူပါ',
    email: 'အီးမေးလ်',
    save: 'သိမ်းဆည်းပါ',
    aboutThisProperty: 'ဤအိမ်ခြံမြေအကြောင်း',
    similarProperties: 'ဆင်တူသည့် အိမ်ခြံမြေများ',
    overview: 'အနှစ်ချုပ်',
    features: 'လုပ်ဆောင်ချက်များ',
    contact: 'ဆက်သွယ်ရန်',
    built: 'ဆောက်လုပ်ပြီး',
    area: 'ဧရိယာ',
    parking: 'ကားရပ်နားရန်',
    cars: 'ကား',
    contactOwner: 'ပိုင်ရှင်ကို ဆက်သွယ်ပါ',
    callOwner: 'ပိုင်ရှင်ကို ဖုန်းခေါ်ပါ',
    chatOnViber: 'Viber တွင် စကားပြောပါ',
    signInToContact: 'ပိုင်ရှင်ကို ဆက်သွယ်ရန် ဝင်ရောက်ပါ',
    addNewProperty: 'အိမ်ခြံမြေအသစ် ထည့်ပါ',
    editProperty: 'အိမ်ခြံမြေ ပြင်ဆင်ပါ',
    fillDetails: 'သင့်အိမ်ခြံမြေကို စာရင်းတင်ရန် အသေးစိတ်ဖြည့်ပါ',
    propertyInfo: 'အိမ်ခြံမြေ အချက်အလက်',
    basicDetails: 'အခြေခံ အသေးစိတ်',
    specifications: 'သတ်မှတ်ချက်များ',
    sizeAndLayout: 'အရွယ်အစားနှင့် အပြင်အဆင်',
    description: 'ဖော်ပြချက်',
    tellUsMore: 'ပိုမိုပြောပြပါ',
    media: 'မီဒီယာ',
    uploadPhotos: 'ဓာတ်ပုံများ တင်ပါ',
    propertyTitle: 'အိမ်ခြံမြေ ခေါင်းစဉ်',
    listingType: 'စာရင်းအမျိုးအစား',
    forSale: 'ရောင်းရန်',
    forRent: 'ငှားရန်',
    price: 'စျေးနှုန်း (MMK)',
    township: 'မြို့နယ်',
    selectLocation: 'တည်နေရာ ရွေးပါ',
    sqftLabel: 'စတုရန်းပေ',
    address: 'လိပ်စာ',
    fullAddress: 'အိမ်ခြံမြေ လိပ်စာ အပြည့်အစုံ',
    descriptionLabel: 'ဖော်ပြချက်',
    descPlaceholder: 'သင့်အိမ်ခြံမြေကို အသေးစိတ် ဖော်ပြပါ...',
    featuresLabel: 'လုပ်ဆောင်ချက်များနှင့် အဆင်ပြေမှုများ',
    dragDrop: 'သင့်ဓာတ်ပုံများကို ဒီမှာ ဆွဲထည့်ပါ',
    orClickToBrowse: 'သို့မဟုတ် ကြည့်ရန် နှိပ်ပါ',
    chooseFiles: 'ဖိုင်များ ရွေးပါ',
    uploadAtLeast: 'အနည်းဆုံး ဓာတ်ပုံ ၁ ပုံ တင်ပါ။ အကြံပြုအရွယ်အစား- 1200x800px',
    previous: 'နောက်သို့',
    next: 'ရှေ့သို့',
    submitForApproval: 'အတည်ပြုချက်အတွက် တင်သွင်းပါ',
    propertySubmitted: 'အိမ်ခြံမြေ တင်သွင်းပြီးပါပြီ!',
    submittedDesc: 'သင့်အိမ်ခြံမြေကို အတည်ပြုချက်အတွက် တင်သွင်းပြီးပါပြီ။',
    redirecting: 'ဒက်ရှ်ဘုတ်သို့ ပြန်ညွှန်နေပါသည်...',
    adminDashboard: 'Admin ဒက်ရှ်ဘုတ်',
    totalUsers: 'စုစုပေါင်း အသုံးပြုသူ',
    totalProperties: 'စုစုပေါင်း အိမ်ခြံမြေ',
    pendingApprovals: 'စောင့်ဆိုင်းနေသည့် အတည်ပြုချက်',
    manageData: 'ဒေတာ စီမံပါ',
    approve: 'အတည်ပြုပါ',
    reject: 'ငြင်းဆိုပါ',
    featuresAmenities: 'လုပ်ဆောင်ချက်များနှင့် အဆင်ပြေမှုများ',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('urbannest-language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('urbannest-language', language);
    document.documentElement.lang = language === 'my' ? 'my' : 'en';
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    if (value) return value;
    if (language !== 'en') {
      let fallback: any = translations.en;
      for (const k of keys) {
        fallback = fallback?.[k];
      }
      if (fallback) return fallback;
    }
    return key;
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'my' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
